name: Deploy post for review

on:
  workflow_run:
    workflows: ["filter-test-dev"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

# jobs:
#   upload:
#     runs-on: ubuntu-latest
#     if: >
#       github.event.workflow_run.event == 'pull_request' &&
#       github.event.workflow_run.conclusion == 'success'
#     steps:
#       - name: 'Download artifact'
#         uses: actions/github-script@v3.1.0
#         with:
#           script: |
#             var artifacts = await github.actions.listWorkflowRunArtifacts({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                run_id: ${{github.event.workflow_run.id }},
#             });
#             var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
#               return artifact.name == "pr"
#             })[0];
#             var download = await github.actions.downloadArtifact({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                artifact_id: matchArtifact.id,
#                archive_format: 'zip',
#             });
#             var fs = require('fs');
#             fs.writeFileSync('${{github.workspace}}/site.zip', Buffer.from(download.data));
#       - run: unzip site.zip
#       - name: Setup AWS CLI
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-west-1
#       - run: |
#         aws s3 sync --region eu-west-1 --acl public-read _site s3://iclr-blogposts-2024/${{ github.event.pull_request.title }}